FROM amazoncorretto:11-alpine-jdk
LABEL maintainer="Sachini  Jayasinghe S.L  IT19126234 2022_REG_08"
COPY target/order-service-0.0.1-SNAPSHOT.jar order-service-0.0.1.jar
ENTRYPOINT ["java","-jar","/order-service-0.0.1.jar"]