#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM amazoncorretto:11-alpine-jdk
LABEL maintainer="Rukshan99  Jayasekara R.T.R  IT19129204 2022_REG_08"
COPY target/recommender-engine-service-0.0.1-SNAPSHOT.jar recommender-engine-service-0.0.1.jar
ENTRYPOINT ["java","-jar","/recommender-engine-service-0.0.1.jar"]