name: CICD Eureka Server

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eureka-server
        
    steps:
      - 
        uses: actions/checkout@v3
      - 
        run: mkdir -p target
      - 
        name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - 
        name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      
      -
        name: Upload build artifacts       
        uses: actions/upload-artifact@v2
        with:        
          path: staging
          if-no-files-found: error
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eureka-server
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11' 

      - name: Update version
        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_RUKSHAN }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_RUKSHAN }}
      - 
        name: Download artifact
        uses: actions/download-artifact@v2

      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rukshan99/eureka-server:v${{github.run_number}}
