name: CICD Recommender Engine Service

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: recommender-engine-service
        
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_RUKSHAN }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_RUKSHAN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: recommender-engine-service
          file: recommender-engine-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME_RUKSHAN }}/recommender-engine-service:latest
